config/routes.rb
Rbflow::Application.routes.draw do
  get "searches/index"

  match '/auth/:provider/callback', :to => 'authentications#create'
  match '/sign_in', :to => 'sessions#new'
  match '/sign_out', :to => 'sessions#destroy'
  
  resources :sessions, :only => [ :new, :destroy ]
  resources :pages, :only => :show
  resources :searches, :only => :index
  resources :users do
    member do
      put 'approve'
      put 'unapprove'
    end
    resources :authentications, :only => :destroy
  end
  resources :items do
    resources :comments
  end
  
  root :to => "items#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = {
    :user  => 0,
    :admin => 1
  }
  ROLES.each_pair {|role, code| define_method("#{role}?") { self.role == code } }
  
  has_many :authentications, :dependent => :destroy
  has_many :items, :dependent => :nullify
  has_many :comments, :dependent => :destroy
  
  attr_protected :role
  
  def self.create_with_omniauth!(auth)
    self.create! do |user|
      user.name       = auth["info"]["name"]
      user.email      = auth["info"]["email"]
      user.avatar_url = auth["info"]["image"]
    end
  end
  
  def approved?
    !self.approved_at.nil?
  end
  
  def approve!
    self.update_attributes(:approved_at => Time.zone.now)
    self
  end
  
  def unapprove!
    self.update_attributes(:approved_at => nil)
    self
  end
  
  def guest?
    self.new_record?
  end
  
  def me?(user)
    self.id == user.id
  end
  
  def providers
    self.authentications.collect(&:provider)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  
  respond_to :html
  
  def index
    respond_with(@users = User.order("created_at DESC").page(params[:page]).per(20))
  end
    
  def show
    respond_with(@user = current_user)
  end
  
  def approve
    respond_with(@user.approve!, :location => users_url)
  end
  
  def unapprove
    respond_with(@user.unapprove!, :location => users_url)
  end
  
  def destroy
    respond_with(@user.destroy)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<section class="grid_2">
  <h1><%= t(".title") %></h1>
</section>
<section class="grid_10">
  <table width="100%" class="users">
  <% for user in @users %>
    <tr>
      <td width="10%" style="text-align:center"><%= image_tag avatar_url(user), :size => "48x48", :alt => user.name, :class => "avatar" %></td>
      <td width="60%">
        <%= user.name %><br />
        <%= mail_to user.email, nil, :encode => "hex" %>
      </td>
      <td width="30%" style="text-align:right">
        <%= (user.approved?) ? link_to(t(".unapprove"), unapprove_user_url(user), :method => :put, :class => "small button") : link_to(t(".approve"), approve_user_url(user), :method => :put, :class => "small button") %>
        <%= link_to t(".destroy"), user, :method => :delete, :confirm => t("layouts.commons.destroy_confirmation", :subject => user.name), :class => "small button" %>
      </td>
    </tr>
  <% end %>
  </table>
  <%= paginate @users %>
</section>

app/views/users/show.html.erb
<% content_for :title, t(".title") %>

<section class="grid_1">
  <%= image_tag avatar_url(@user), :size => "48x48", :alt => @user.name, :class => "avatar" %>
  <p><%= link_to t("layouts.application.sign_out"), sign_out_url, :class => "link-with-icon" %></p>
</section>
<section class="grid_6">
  <h1 class="header-with-comment"><%= @user.name %> <span><%= @user.email %></span></h1>
</section>
<section class="grid_5">
  <h2><%= t(".providers") %>:</h2>
  <table width="100%" class="providers">
    <!-- not installed providers -->
    <% for provider in Authentication::PROVIDERS.keys - @user.providers %>
    <tr>
      <td width="20%"><%= image_tag("#{provider}_64.png", :size => "64x64") %></td>
      <td width="60%"><%= Authentication::PROVIDERS[provider] %></td>
      <td width="20%"><%= link_to t(".add_provider"), "/auth/#{provider}", :class => "positive small button min-width uppercase" %></td>
    </tr>
    <% end %>
    <!-- installed providers -->
    <% for authentication in @user.authentications %>
    <tr>
      <td width="20%"><%= image_tag("#{authentication.provider}_64.png", :size => "64x64") %></td>
      <td width="60%"><%= authentication.provider_name %></td>
      <td width="20%"><%= link_to(t(".remove_provider"), [current_user, authentication], :method => :delete, :class => "negative small button min-width uppercase") if can?(:destroy, authentication) %></td>
    </tr>
    <% end %>
  </table>
</section>