config/routes.rb
Rbflow::Application.routes.draw do
  get "searches/index"

  match '/auth/:provider/callback', :to => 'authentications#create'
  match '/sign_in', :to => 'sessions#new'
  match '/sign_out', :to => 'sessions#destroy'
  
  resources :sessions, :only => [ :new, :destroy ]
  resources :pages, :only => :show
  resources :searches, :only => :index
  resources :users do
    member do
      put 'approve'
      put 'unapprove'
    end
    resources :authentications, :only => :destroy
  end
  resources :items do
    resources :comments
  end
  
  root :to => "items#index"
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy

  validates_presence_of :title, :markdown
  validates_presence_of :user_id, :on => :create

  attr_accessible :title, :markdown

  before_save :assign_html, :if => :markdown?

  scope :recent, includes(:user).order("created_at desc")

  def author?(user)
    self.user_id == user.id
  end

  def author_name
    self.user.blank? ? "" : self.user.name
  end

  private

  def assign_html
    self.html = RDiscount.new(self.markdown, :filter_styles, :filter_html, :autolink).to_html
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource

  respond_to :html
  respond_to :rss, :only => :index
  
  def index
    respond_with(@items = Item.recent.page(params[:page]).per(10))
  end
  
  def new
    respond_with(@item = current_user.items.new)
  end
  
  def create
    @item = current_user.items.create(params[:item]) and flash[:notice] = t("items.create.successful")
    respond_with(@item)
  end
  
  def show
    respond_with(@item)
  end
  
  def edit
    respond_with(@item)
  end
  
  def update
    @item.update_attributes(params[:item]) and flash[:notice] = t("items.update.successful")
    respond_with(@item)
  end
  
  def destroy
    @item.destroy and flash[:notice] = t("items.destroy.successful")
    respond_with(@item)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div>
  <%= f.text_field :title, :placeholder => t("activerecord.attributes.item.title"), :autofocus => true %>
</div>
<div id="wmd-button-bar"></div>
<div>
  <%= f.text_area :markdown, :placeholder => t("activerecord.attributes.item.markdown") %>
</div>
<% content_for :footer_js do %>
  <script type="text/javascript">
    function updateTitlePreview() {
      $("#title-preview").text($(this).val());
    };
    
    $("#item_title").keyup(updateTitlePreview);
    
    setup_wmd({
      input: "item_markdown"
    });
  </script>
<% end %>

app/views/items/_preview.html.erb
<div class="wmd-preview">
  <header>Просмотр</header>
  <h1 id="title-preview"><%= item.title %></h1>
  <div id="wmd-preview"><%=raw item.html %></div>
</div>

app/views/items/edit.html.erb
<% content_for :title, t(".title") %>

<section class="grid_6 preview">
  <%= render :partial => "preview", :locals => { :item => @item } %>
</section>
<section class="grid_6 form">
  <%= form_for @item do |f| %>
    <%= render :partial => "form", :locals => { :f => f } %>
    <div class="buttons">
      <%= f.submit t(".update"), :disable_with => t(".processing") %>
      <%= link_to t(".cancel"), :back %>
    </div>
  <% end %>
</section>

app/views/items/index.html.erb
<% content_for :title, t(".title") %>

<% if params[:page].blank? %>
  <section class="event container_12 clearfix">
    <!-- Banner960x120 -->
    <div id="div-gpt-ad-1363161654747-0">
      <script type='text/javascript'>
        googletag.cmd.push(function() { googletag.display('div-gpt-ad-1363161654747-0'); });
      </script>
    </div>
  </section>
<% end %>

<% if !@items.blank? %>
  <% @items.group_by{ |item| item.created_at.to_date }.each do |created_at, items| %>
  <section class="day container_12 clearfix">
    <time datetime="<%= created_at.to_s(:db) %>" pubdate="pubdate" class="grid_2">
      <span class="date-day"><%= created_at.strftime("%d") %></span><span class="date-month">.<%= created_at.strftime("%m") %></span> <span class="date-year"><%= created_at.strftime("%Y") %></span>
    </time>
    <section class="articles grid_8">
      <% for item in items %>
      <article>
        <header>
          <%= link_to item.title, item %><span><%= item.author_name %></span>
        </header>
        <aside>
          <ul>
            <li><a href="#" onclick="Evernote.doClip({styling:'none',suggestNotebook:'rubyflow.ru',providerName:'rubyflow.ru',contentId:'item-<%= item.id %>-html',url:'<%= item_url(item) %>',title:'<%= escape_javascript item.title %>'}); return false;"><img src="http://static.evernote.com/site-mem-16.png" alt="Сохранить в Evernote" style="vertical-align:bottom"></a></li>
          </ul>
        </aside>
        <%=raw item.html %>
        <% if !item.comments.blank? %>
        <section class="comments clearfix">
          <header class="grid_2"><%= link_to t(".comments"), item_url(item, :anchor => "comments") %></header>
          <section class="grid_6">
            <article class="comment">
              <header>
                <time datetime="<%= item.comments.last.created_at.to_s(:db) %>" pubdate="pubdate"><%= item.comments.last.created_at.strftime("%d.%m.%Y") %></time>
                <%= item.comments.last.user.name %>
              </header>
              <%=raw item.comments.last.html %>
            </article>
          </section>
        </section>
        <% end %>
      </article>
      <% end %>
    </section>
  </section>
  <% end %>
  <%= paginate @items %>
<% end %>

app/views/items/new.html.erb
<% content_for :title, t(".title") %>

<section class="grid_6 preview">
  <%= render :partial => "preview", :locals => { :item => @item } %>
</section>
<section class="grid_6 form">
  <%= form_for @item do |f| %>
    <%= render :partial => "form", :locals => { :f => f } %>
    <div class="buttons">
      <%= f.submit t(".create"), :disable_with => t(".processing") %>
      <%= link_to t(".cancel"), :back %>
    </div>
  <% end %>
</section>

app/views/items/show.html.erb
<% content_for :title, @item.title %>
<% content_for :meta_description, @item.title %>
<% content_for :meta_author, @item.author_name %>

<section class="grid_2 day">
  <time datetime="<%= @item.created_at.to_s(:db) %>" pubdate="pubdate">
    <span class="date-day"><%= @item.created_at.strftime("%d") %></span><span class="date-month">.<%= @item.created_at.strftime("%m") %></span> <span class="date-year"><%= @item.created_at.strftime("%Y") %></span>
</time>
</section>
<section class="grid_8">
  <article>
    <header>
      <%= @item.title %><span><%= @item.author_name %></span>
    </header>
    <aside>
      <ul>
        <li><a href="#" onclick="Evernote.doClip({styling:'none',suggestNotebook:'rubyflow.ru',providerName:'rubyflow.ru',contentId:'item-<%= @item.id %>-html',url:'<%= item_url(@item) %>',title:'<%= escape_javascript @item.title %>'}); return false;"><img src="http://static.evernote.com/site-mem-16.png" alt="Сохранить в Evernote" style="vertical-align:bottom"></a></li>
      </ul>
    </aside>
    <section id="item-<%= @item.id %>-html"><%= @item.html.html_safe %></section>
    <section class="comments clearfix">
      <header class="grid_2"><a name="comments"></a><%= t(".comments") %></header>
      <section class="grid_6">
        <% for comment in @item.comments %>
          <%= render comment %>
        <% end %>
        <% if can?(:create, Comment) %>
          <section id="item-<%= @item.id %>-new-comment" class="new-comment">
            <%= render(:partial => "comments/new", :locals => { :item => @item, :comment => @item.comments.new }) %>
          </section>
          <p><%= link_to "#{icon_tag("comment-add")} #{t(".new_comment")}".html_safe, nil, :onclick => "$('#item-#{@item.id}-new-comment').slideDown('slow');$(this).hide('fast');return false;", :class => "link-with-icon" %></p>
        <% else %>
          <%= t(".please_sign_in_to_add_comment") %> <%= link_to t("layouts.application.sign_in"), sign_in_url %>
        <% end %>
      </section>
    </section>
  </article>
</section>
<section class="grid_2">
  <% if can?(:edit, @item) %>
  <ul class="admin-buttons">
    <%= content_tag :li, link_to("#{icon_tag("item-edit")} #{t(".edit")}".html_safe, edit_item_url(@item), :class => "link-with-icon") if can?(:edit, @item) %>
    <%= content_tag :li, link_to("#{icon_tag("item-remove")} #{t(".destroy")}".html_safe, item_url(@item), :method => :delete, :confirm => t("layouts.commons.destroy_confirmation", :subject => @item.title), :class => "link-with-icon") if can?(:destroy, @item) %>
  </ul>
  <% end %>
</section>