config/routes.rb
Rbflow::Application.routes.draw do
  get "searches/index"

  match '/auth/:provider/callback', :to => 'authentications#create'
  match '/sign_in', :to => 'sessions#new'
  match '/sign_out', :to => 'sessions#destroy'
  
  resources :sessions, :only => [ :new, :destroy ]
  resources :pages, :only => :show
  resources :searches, :only => :index
  resources :users do
    member do
      put 'approve'
      put 'unapprove'
    end
    resources :authentications, :only => :destroy
  end
  resources :items do
    resources :comments
  end
  
  root :to => "items#index"
end

app/models/ability.rb
class Ability  
  include CanCan::Ability  
  
  def initialize(user)
    user ||= User.new     # guest user

    if user.admin?
      can :manage, :all
    else
      can :read, Item

      if !user.guest?
        can(:update, Item) { |item| item.author?(user) && item.created_at.today? }
        can(:destroy, Item) { |item| item.author?(user) && item.created_at.today? }
        can(:create, [Item, Comment])
        can(:show, User) { |_user| _user.me?(user) }
        can(:destroy, Authentication) { |authentication| authentication.user_id == user.id && user.authentications.size > 1 }
      end
    end
  end  
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  PROVIDERS = {
    "open_id" => "OpenID",
    "github"  => "GitHub",
    "twitter" => "Twitter"
  }

  belongs_to :user

  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.create_with_omniauth!(auth, user = nil)
    user ||= User.create_with_omniauth!(auth)
    self.create! do |authentication|
      authentication.user = user
      authentication.uid = auth['uid']
      authentication.provider = auth['provider']
    end
  end

  def provider_name
    PROVIDERS[self.provider]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :item
  belongs_to :user
  
  validates_presence_of :item_id, :user_id, :markdown
  
  attr_accessible :markdown
  
  before_save :assign_html, :if => :markdown?
  
  private
  
  def assign_html
    self.html = RDiscount.new(self.markdown, :filter_styles, :filter_html, :autolink).to_html
  end  
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy

  validates_presence_of :title, :markdown
  validates_presence_of :user_id, :on => :create

  attr_accessible :title, :markdown

  before_save :assign_html, :if => :markdown?

  scope :recent, includes(:user).order("created_at desc")

  def author?(user)
    self.user_id == user.id
  end

  def author_name
    self.user.blank? ? "" : self.user.name
  end

  private

  def assign_html
    self.html = RDiscount.new(self.markdown, :filter_styles, :filter_html, :autolink).to_html
  end
end

app/models/search.rb
class Search
  def initialize(resource = Item)
    @resource = resource
  end

  def perform(query = '')
    @resource.basic_search(:html => query)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = {
    :user  => 0,
    :admin => 1
  }
  ROLES.each_pair {|role, code| define_method("#{role}?") { self.role == code } }
  
  has_many :authentications, :dependent => :destroy
  has_many :items, :dependent => :nullify
  has_many :comments, :dependent => :destroy
  
  attr_protected :role
  
  def self.create_with_omniauth!(auth)
    self.create! do |user|
      user.name       = auth["info"]["name"]
      user.email      = auth["info"]["email"]
      user.avatar_url = auth["info"]["image"]
    end
  end
  
  def approved?
    !self.approved_at.nil?
  end
  
  def approve!
    self.update_attributes(:approved_at => Time.zone.now)
    self
  end
  
  def unapprove!
    self.update_attributes(:approved_at => nil)
    self
  end
  
  def guest?
    self.new_record?
  end
  
  def me?(user)
    self.id == user.id
  end
  
  def providers
    self.authentications.collect(&:provider)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource :item
  load_and_authorize_resource :comment, :through => :item
  
  respond_to :js
  
  def create
    @comment.user = current_user
    respond_with(@item, @comment.save)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource

  respond_to :html
  respond_to :rss, :only => :index
  
  def index
    respond_with(@items = Item.recent.page(params[:page]).per(10))
  end
  
  def new
    respond_with(@item = current_user.items.new)
  end
  
  def create
    @item = current_user.items.create(params[:item]) and flash[:notice] = t("items.create.successful")
    respond_with(@item)
  end
  
  def show
    respond_with(@item)
  end
  
  def edit
    respond_with(@item)
  end
  
  def update
    @item.update_attributes(params[:item]) and flash[:notice] = t("items.update.successful")
    respond_with(@item)
  end
  
  def destroy
    @item.destroy and flash[:notice] = t("items.destroy.successful")
    respond_with(@item)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  respond_to :html

  def show
    @page = params[:id]
    render(:layout => false, :file => "public/404.html", :status => :not_found) unless %w(about).include?(@page)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  respond_to :html

  def index
    @search = Search.new(Item)
    respond_with @items = @search.perform(params[:q]).page(params[:page]).per(20)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => t("sessions.destroy.successful")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  
  respond_to :html
  
  def index
    respond_with(@users = User.order("created_at DESC").page(params[:page]).per(20))
  end
    
  def show
    respond_with(@user = current_user)
  end
  
  def approve
    respond_with(@user.approve!, :location => users_url)
  end
  
  def unapprove
    respond_with(@user.unapprove!, :location => users_url)
  end
  
  def destroy
    respond_with(@user.destroy)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Flash messages as html
  def flash_messages(messages = {})
    messages = flash unless flash.empty?
    messages.collect{ |kind, message| flash_message(message, kind) }.join.html_safe
  end
  
  def flash_message(message, kind = :notice)
    content_tag :div, message, :class => "message #{kind.to_s}"
  end
  
  def markdown(source)
    source.blank? ? "" : RDiscount.new(source).to_html.html_safe
  end
  
  def avatar_url(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      default_url = "#{root_url}images/guest.png"
      if !user.email.blank?
        gravatar_id = Digest::MD5::hexdigest(user.email).downcase  
        "http://gravatar.com/avatar/#{gravatar_id}.png?s=48&d=#{CGI.escape(default_url)}"
      else
        default_url
      end
    end
  end
  
  def icon_tag(icon)
    content_tag :i, nil, :class => "icon #{icon}"
  end
  
  def years_tag(from = 2008, to = Date.current.year)
    if from != to
      "#{from}&mdash;#{to}".html_safe
    else
      from.to_s
    end
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale -%>">
  <head>
    <meta charset="utf-8" />
    <meta name="description" content="<%= yield(:meta_description).blank? ? t(".meta_description") : yield(:meta_description) %>" />
    <meta name="keywords" content="<%= yield(:meta_keywords).blank? ? t(".meta_keywords") : yield(:meta_keywords) %>" />
    <meta name="author" content="<%= yield(:meta_author).blank? ? t(".meta_author") : yield(:meta_author) %>" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <link rel="alternate" type="application/rss+xml" title="RubyFlow.ru" href="http://feedproxy.google.com/rubyflowru" />
    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tag %>
    <title><%= "#{yield(:title)} &mdash; ".html_safe unless yield(:title).blank? -%><%= t('.title') -%></title>
    <script type='text/javascript'>
    var googletag = googletag || {};
    googletag.cmd = googletag.cmd || [];
    (function() {
    var gads = document.createElement('script');
    gads.async = true;
    gads.type = 'text/javascript';
    var useSSL = 'https:' == document.location.protocol;
    gads.src = (useSSL ? 'https:' : 'http:') +
    '//www.googletagservices.com/tag/js/gpt.js';
    var node = document.getElementsByTagName('script')[0];
    node.parentNode.insertBefore(gads, node);
    })();
    </script>

    <script type='text/javascript'>
    googletag.cmd.push(function() {
    googletag.defineSlot('/7221921/Banner620x120', [960, 120], 'div-gpt-ad-1363161654747-0').addService(googletag.pubads());
    googletag.pubads().enableSingleRequest();
    googletag.enableServices();
    });
    </script>
  </head>
  <body>
    <section id="flash" class="flash" style="display:none;"><%= flash_messages %></section>
    <% if can?(:manage, :all) %>
    <nav id="control-panel" class="control-panel container_12 clearfix">
      <ul>
        <li><%= link_to t(".users"), users_url %></li>
      </ul>
    </nav>
    <% end %>
    <header id="header" class="container_12 clearfix">
      <section class="logo grid_2"><%= link_to_if !current_page?(root_url), "Ruby<span>Flow</span>".html_safe, root_url %></section>
      <section class="menu grid_8">
        <nav>
          <ul>
            <li><%= link_to t(".new_item"), new_item_url %></li>
            <li><%= link_to t(".vacancies"), "http://rubyjobs.ru" %></li>
            <li><%= link_to t(".about"), page_url(:id => "about") %></li>
            <li><%= link_to image_tag("feed.png", :size => "16x16"), "http://feeds.feedburner.com/rubyflowru" %></li>
            <li>
              <a href="https://twitter.com/rubyflowru" class="twitter-follow-button" data-show-count="false" data-lang="ru" data-show-screen-name="false" data-width="65px">Читать @rubyflowru</a>
              <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </li>
          </ul>
        </nav>
      </section>
      <section class="search form grid_2">
        <%= form_tag searches_url, :method => :get do %>
          <%= search_field_tag :q, params[:q], :placeholder => t(".search"), :results => 5 %>
        <% end %>
      </section>
      <section class="account">
        <%= signed_in? ? link_to(t(".account"), user_url(current_user)) : link_to(t(".sign_in"), sign_in_url) %>
      </section>
    </header>
    <section id="content" class="content container_12 clearfix">
      <%= yield %>
    </section>
    <footer id="footer" class="container_12 clearfix">
      <section class="grid_2">
        <p>
          &copy;&nbsp;<%= years_tag %><br>
          <a href="http://sul.im">Alex Sulim</a>
        </p>
      </section>
      <section class="grid_4">
        <p>
          <%= link_to image_tag('digitalocean-badge-gray.png', :size => '140x39'), 'http://www.digitalocean.com' %>
        </p>
      </section>
      <section class="grid_4">
        <p>
          <%= link_to image_tag('travis-ci50x50.png', :size => '50x50'), 'http://travis-ci.org/', :style => 'float:left;margin-right:10px;' %>
          Travis CI&nbsp;&mdash; простой и мощный сервис непрерывной интеграции для ваших проектов с открытым кодом.
          <%= link_to 'http://travis-ci.org', 'http://travis-ci.org' %>
        </p>
      </section>
      <section class="grid_2 counters">
        <a href="http://feeds.feedburner.com/rubyflowru" style="display:inline-block;vertical-align:top;" title="Подпишись на RSS"><img src="http://feeds.feedburner.com/~fc/rubyflowru?bg=eeeeee&amp;fg=444444&amp;anim=0" height="26" width="88" style="border:0" alt="" /></a>
      </section>
    </footer>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript">
      $('pre').each(function(i, e) { hljs.highlightBlock(e, '    ')});
    </script>
    <%= yield(:footer_js) %>

    <% if Rails.env.production? %>
      <%= javascript_include_tag "http://static.evernote.com/noteit.js", :cache => false %>
      <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-391915-11']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
      </script>
    <% end %>
  </body>
</html>

app/views/pages/show.html.erb
<% content_for :title, t(".#{@page}.title") %>

<section class="grid_2">
  &nbsp;
</section>
<section class="grid_8">
  <h1><%= t(".#{@page}.title") %></h1>
  <%= RDiscount.new(t(".#{@page}.markdown")).to_html.html_safe %>
</section>
<section class="grid_2">
  &nbsp;
</section>